### PR TITLE
UpSet plot for cohort overlaps

### LINKED ISSUE #27: analysis: cohortsOverlap: viewer

### PR DESCRIPTION
**Pull request by siirtola**
What is still missing:
- there is no UI to remove a cohort - what would be the use case for this?

### CODE REVIEW

**Comment by javier-gracia-tabuenca-tuni** [comment]
can you record the new packages that you added with 
renv::snapshot() 
?

**Comment by siirtola** [comment]
Sorry, I do it right away!

**Comment by javier-gracia-tabuenca-tuni** [comment]
getting an error
image
i think some functions are missing the package 
fluidRow -> shiny::fluidRow ?

can you check it runs without loading any library (dont do library(shiny) before running )

**Review by javier-gracia-tabuenca-tuni — APPROVED** [review]
Thanks, now works very well

**Comment by siirtola** [comment]
Btw, are these branches supposed to be deleted after merge? By me or by you?

**Pull request merged**
